# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atoj_games', '0002_remove_developer_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='api_key',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
